x-dns-settings: &dns-logic
  extra_hosts:
    - "host.docker.internal:host-gateway"
  dns:
    - ${DOCKER_GATEWAY}

services:
  nginxproxymanager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${DATA_DIR}/NginxProxy/data:/data
      - ${DATA_DIR}/NginxProxy/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-tier

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/heimdall:/config
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VAAPI_DRIVER=iHD
      - DISPLAY=:0
    devices:
      - /dev/dri
    volumes:
      - ${DATA_DIR}/jellyfin:/config
      - ${BULK_DIR}/jellyfin/shows:/data/tvshows
      - ${BULK_DIR}/jellyfin/movies:/data/movies
      - ${BULK_DIR}/jellyfin/live:/data/live
    ports:
      - "7359:7359/udp"
      - "1900:1900/udp"
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - DNSMASQ_LISTENING=all
      - FTLCONF_LOCAL_IPV6=${PIHOLE_IPV6}
    volumes:
      - '${DATA_DIR}/pihole/etc-pihole:/etc/pihole'
      - '${DATA_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - proxy-tier

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=82
    volumes:
      - ${DATA_DIR}/qbittorrent:/config
      - ${BULK_DIR}:/HDD
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/syncthing:/config
      - ${MEDIA_DIR}:/data
    ports:
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/sonarr:/config
      - ${BULK_DIR}:/HDD
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/radarr:/config
      - ${BULK_DIR}/:/HDD
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/prowlarr:/config
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/bazarr:/config
      - ${BULK_DIR}:/HDD
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    volumes:
      - ${DATA_DIR}/jdownloader:/config:rw
      - ${BULK_DIR}/jdownloader:/output:rw
      - ${BULK_DIR}/jdownloader:/output:rw
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/jellyseerr:/app/config
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data
    <<: *dns-logic
    networks:
      - proxy-tier

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --cleanup
      --interval 3600
    environment:
      - DOCKER_API_VERSION=1.54
    <<: *dns-logic
    networks:
      - proxy-tier

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    volumes:
      - ${DATA_DIR}/excalidraw/:/data
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  stirlingpdf:
    container_name: stirlingpdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest-fat
    volumes:
      - ${DATA_DIR}/stirlingpdf/trainingData:/usr/share/tessdata
      - ${DATA_DIR}/stirlingpdf/extraConfigs:/configs
      - ${DATA_DIR}/stirlingpdf/customFiles:/customFiles/
      - ${DATA_DIR}/stirlingpdf/logs:/logs/
      - ${DATA_DIR}/stirlingpdf/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_US
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  prunemate:
    image: anoniemerd/prunemate:latest
    container_name: prunemate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/prunemate/logs:/var/log
      - ${DATA_DIR}/prunemate/config:/config
    environment:
      - PRUNEMATE_TZ=${TZ}
      - PRUNEMATE_TIME_24H=false
    restart: unless-stopped
    <<: *dns-logic
    networks:
      - proxy-tier

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ${MEDIA_DIR}:/mnt/media:z
    command: >
      -n
      -s "Media;/mnt/media;yes;no;yes;all;all;all"

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: chuwi
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${DATA_DIR}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-routes=${TS_ROUTES} --accept-dns=false
      - TS_STATE_DIR=/var/lib/tailscale

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${BULK_DIR}/immich:/data
      - ${BULK_DIR}/immich:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - IMMICH_MACHINE_LEARNING_ENABLED=false
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    <<: *dns-logic
    networks:
      - proxy-tier

  immich_redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: always
    <<: *dns-logic
    networks:
      - proxy-tier

  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ${DATA_DIR}/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    <<: *dns-logic
    networks:
      - proxy-tier

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS}
      - DOMAIN=${VAULTWARDEN_DOMAIN}
      - DATABASE_URL=data/vaultwarden.db
    volumes:
      - ${DATA_DIR}/vaultwarden:/data
    <<: *dns-logic
    networks:
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge
